// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fffhaxyrkvqanovmeebj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmZmhheHlya3ZxYW5vdm1lZWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTMxNDAsImV4cCI6MjA2MDIyOTE0MH0.dax1wdoGFl4DlpQVPvTFPZCFW_ao22X6i5HQlLN4ik4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);